### ISSUE TITLE
Multiplying a multivariate polynomial in one variable by a constant unexpectedly changes its type to univariate

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#38089]
### Steps To Reproduce

The code:

```
K = PolynomialRing(ZZ,1,'z')
z = K.gen(0)
print( z.parent() )
print( (z*QQ.one()).parent() )
```

prints

> Multivariate Polynomial Ring in z over Integer Ring
> Univariate Polynomial Ring in z over Rational Field

### Expected Behavior

Multiplication by a constant should not turn a multivariate polynomial into univariate one. That is, `z*QQ.one()` should be an element of `Multivariate Polynomial Ring in z over Rational Field`.

### Actual Behavior

`z*QQ.one()` unexpectedly becomes a univariate polynomial.

### Environment

```markdown
- **OS**: Ubuntu 22.04.4 LTS
- **Sage Version**: 10.3
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by grhkm21** [comment]
The PR should fix it. Cheers 🍻

**Comment by grhkm21** [comment]
See discussion at #38106.

**Comment by maxale** [comment]
The issue is closed as "completed". What is exactly completed here? The issue is still stands.

**Comment by tscrim** [comment]
I have reopened it.
