### ISSUE TITLE
Test suite regressions in the meson build

### ISSUE THREAD

**Issue by antonio-rojas** [sagemath/sage#39872]
Meta issue to track test suite regessions with the meson build. The failures happen when running an installed sage - they may not be reproducible when running the test suite from the source tree.

For distro packaging, it is important to run the test suite from an installed sage to make sure everything works properly. Some of the failures may not have any noticeable effect for users, but still cause noise in the test suite that may prevent actual issues from getting noticed.

**Comment by tobiasdiez** [comment]
In https://github.com/sagemath/sage/pull/40158, I've discovered a few more issues. Namely,
> sage-runtests --long --warn-long 30.0 --random-seed=195123039357273489794946592323936759837 src/sage/misc/sageinspect.py  # 2 doctests failed

Since it's not able to relativize to path in `sage_getfile_relative`. I cannot reproduce it in an editable install (ci uses non-editable). Looks like the problem is that `sage_getfile` returns the path to the source folder.

> sage-runtests --long --warn-long 30.0 --random-seed=195123039357273489794946592323936759837 src/sage_docbuild/builders.py  # 28 doctests failed
sage-runtests --long --warn-long 30.0 --random-seed=195123039357273489794946592323936759837 src/sage_docbuild/sphinxbuild.py  # 13 doctests failed
sage-runtests --long --warn-long 30.0 --random-seed=195123039357273489794946592323936759837 src/sage_docbuild/utils.py  # 7 doctests failed

Since `sage_docbuild` is not an installed module. Any opinions about how to fix this best? I really don't want to ship the docbuilding to end-users.

**Comment by antonio-rojas** [comment]
> In [#40158](https://github.com/sagemath/sage/pull/40158), I've discovered a few more issues. Namely,
> 
> > sage-runtests --long --warn-long 30.0 --random-seed=195123039357273489794946592323936759837 src/sage/misc/sageinspect.py  # 2 doctests failed
> 
> Since it's not able to relativize to path in `sage_getfile_relative`. I cannot reproduce it in an editable install (ci uses non-editable). Looks like the problem is that `sage_getfile` returns the path to the source folder.

Won't those be fixed with https://github.com/cython/cython/pull/6755 ?

> > sage-runtests --long --warn-long 30.0 --random-seed=195123039357273489794946592323936759837 src/sage_docbuild/builders.py  # 28 doctests failed
> > sage-runtests --long --warn-long 30.0 --random-seed=195123039357273489794946592323936759837 src/sage_docbuild/sphinxbuild.py  # 13 doctests failed
> > sage-runtests --long --warn-long 30.0 --random-seed=195123039357273489794946592323936759837 src/sage_docbuild/utils.py  # 7 doctests failed
> 
> Since `sage_docbuild` is not an installed module. Any opinions about how to fix this best? I really don't want to ship the docbuilding to end-users.

I've never tested anything in `sage_docbuild`. After https://github.com/sagemath/sage/pull/40686 I can simply do `python -m sage.doctest -a -l` to fully test (only) the installed parts of sage.

**Comment by dkwo** [comment]
With sage 10.8 on Void, I am still getting (among others) two failures in sage/misc/sageinspect.py
```
2026-01-12T08:25:32.1678143Z python3 -m sage.doctest --warn-long 10.0 --random-seed=0 sage/misc/sageinspect.py
2026-01-12T08:25:32.1678962Z **********************************************************************
2026-01-12T08:25:32.1679774Z File "sage/misc/sageinspect.py", line 1329, in sage.misc.sageinspect.sage_getfile_relative
2026-01-12T08:25:32.1680530Z Failed example:
2026-01-12T08:25:32.1680896Z     sage_getfile_relative(sage.rings.rational)
2026-01-12T08:25:32.1681346Z Expected:
2026-01-12T08:25:32.1681648Z     'sage/rings/rational.pyx'
2026-01-12T08:25:32.1681999Z Got:
2026-01-12T08:25:32.1682359Z     '/builddir/sagemath-10.8/src/sage/rings/rational.pyx'
2026-01-12T08:25:32.1682902Z **********************************************************************
2026-01-12T08:25:32.1683663Z File "sage/misc/sageinspect.py", line 1334, in sage.misc.sageinspect.sage_getfile_relative
2026-01-12T08:25:32.1684386Z Failed example:
2026-01-12T08:25:32.1684892Z     sage_getfile_relative(x)                                                  # needs sage.symbolic
2026-01-12T08:25:32.1685541Z Expected:
2026-01-12T08:25:32.1685855Z     'sage/symbolic/expression.pyx'
2026-01-12T08:25:32.1686204Z Got:
2026-01-12T08:25:32.1686597Z     '/builddir/sagemath-10.8/src/sage/symbolic/expression.pyx'
2026-01-12T08:25:33.1093117Z **********************************************************************
2026-01-12T08:25:33.1093723Z 1 item had failures:
2026-01-12T08:25:33.1094188Z    2 of   7 in sage.misc.sageinspect.sage_getfile_relative
2026-01-12T08:25:33.3274494Z     [361 tests, 2 failures, 1.71s wall]
```
which look like they are related to this issue.

**Comment by antonio-rojas** [comment]
> With sage 10.8 on Void, I am still getting (among others) two failures in sage/misc/sageinspect.py
> 
> ```
> 2026-01-12T08:25:32.1678143Z python3 -m sage.doctest --warn-long 10.0 --random-seed=0 sage/misc/sageinspect.py
> 2026-01-12T08:25:32.1678962Z **********************************************************************
> 2026-01-12T08:25:32.1679774Z File "sage/misc/sageinspect.py", line 1329, in sage.misc.sageinspect.sage_getfile_relative
> 2026-01-12T08:25:32.1680530Z Failed example:
> 2026-01-12T08:25:32.1680896Z     sage_getfile_relative(sage.rings.rational)
> 2026-01-12T08:25:32.1681346Z Expected:
> 2026-01-12T08:25:32.1681648Z     'sage/rings/rational.pyx'
> 2026-01-12T08:25:32.1681999Z Got:
> 2026-01-12T08:25:32.1682359Z     '/builddir/sagemath-10.8/src/sage/rings/rational.pyx'
> 2026-01-12T08:25:32.1682902Z **********************************************************************
> 2026-01-12T08:25:32.1683663Z File "sage/misc/sageinspect.py", line 1334, in sage.misc.sageinspect.sage_getfile_relative
> 2026-01-12T08:25:32.1684386Z Failed example:
> 2026-01-12T08:25:32.1684892Z     sage_getfile_relative(x)                                                  # needs sage.symbolic
> 2026-01-12T08:25:32.1685541Z Expected:
> 2026-01-12T08:25:32.1685855Z     'sage/symbolic/expression.pyx'
> 2026-01-12T08:25:32.1686204Z Got:
> 2026-01-12T08:25:32.1686597Z     '/builddir/sagemath-10.8/src/sage/symbolic/expression.pyx'
> 2026-01-12T08:25:33.1093117Z **********************************************************************
> 2026-01-12T08:25:33.1093723Z 1 item had failures:
> 2026-01-12T08:25:33.1094188Z    2 of   7 in sage.misc.sageinspect.sage_getfile_relative
> 2026-01-12T08:25:33.3274494Z     [361 tests, 2 failures, 1.71s wall]
> ```
> 
> which look like they are related to this issue.

Yes, those are known and should be fixed by https://github.com/cython/cython/pull/6755 whenever it is merged.

**Comment by dkwo** [comment]
I see, thanks!

**Comment by dkwo** [comment]
One more thing: using the meson system, there are a few tests
```
sage/misc/session.pyx  # 2 doctests failed
sage/env.py  # 2 doctests failed
sage/repl/load.py  # 2 doctests failed
sage/repl/ipython_tests.py  # 3 doctests failed
sage/rings/tate_algebra_ideal.pyx  # 1 doctest failed
```
that now fail in a similar way with `pkgconfig.exists(blas_lib))`, but they pass if I install `cblas-devel`.
This is with openblas-devel only (which used to work):
```
Run-time dependency cblas found: NO (tried pkgconfig and cmake)
Run-time dependency openblas found: YES 0.3.30
```
Long output example (others are similar):
```
2026-01-12T08:40:17.6763822Z python3 -m sage.doctest --warn-long 10.0 --random-seed=0 sage/misc/session.pyx
2026-01-12T08:40:17.6765267Z **********************************************************************
2026-01-12T08:40:17.6766288Z File "sage/misc/session.pyx", line 293, in sage.misc.session.save_session
2026-01-12T08:40:17.6772298Z Failed example:
2026-01-12T08:40:17.6772693Z     g = cython_lambda('double x', 'x*x + 1.5')
2026-01-12T08:40:17.6773158Z Exception raised:
2026-01-12T08:40:17.6773519Z     Traceback (most recent call last):
2026-01-12T08:40:17.6774290Z       File "sage/misc/cachefunc.pyx", line 1040, in sage.misc.cachefunc.CachedFunction.__call__
2026-01-12T08:40:17.6775078Z         return self.cache[k]
2026-01-12T08:40:17.6775467Z     KeyError: ((), ())
2026-01-12T08:40:17.6775903Z 
2026-01-12T08:40:17.6776220Z     During handling of the above exception, another exception occurred:
2026-01-12T08:40:17.6776921Z 
2026-01-12T08:40:17.6777087Z     Traceback (most recent call last):
2026-01-12T08:40:17.6778381Z       File "/builddir/sagemath-10.8/.xbps-testdir/1768205922/usr/lib/python3.14/site-packages/sage/doctest/forker.py", line 734, in _run
2026-01-12T08:40:17.6779557Z         self.compile_and_execute(example, compiler, test.globs)
2026-01-12T08:40:17.6780167Z         ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-01-12T08:40:17.6781336Z       File "/builddir/sagemath-10.8/.xbps-testdir/1768205922/usr/lib/python3.14/site-packages/sage/doctest/forker.py", line 1158, in compile_and_execute
2026-01-12T08:40:17.6782484Z         exec(compiled, globs)
2026-01-12T08:40:17.6782868Z         ~~~~^^^^^^^^^^^^^^^^^
2026-01-12T08:40:17.6783432Z       File "<doctest sage.misc.session.save_session[9]>", line 1, in <module>
2026-01-12T08:40:17.6784121Z         g = cython_lambda('double x', 'x*x + 1.5')
2026-01-12T08:40:17.6784896Z       File "sage/misc/lazy_import.pyx", line 413, in sage.misc.lazy_import.LazyImport.__call__
2026-01-12T08:40:17.6785695Z         return self.get_object()(*args, **kwds)
2026-01-12T08:40:17.6790394Z       File "/builddir/sagemath-10.8/.xbps-testdir/1768205922/usr/lib/python3.14/site-packages/sage/misc/cython.py", line 566, in cython_lambda
2026-01-12T08:40:17.6791615Z         cython_import_all(tmpfile, d, verbose=verbose, **kwds)
2026-01-12T08:40:17.6792222Z         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-01-12T08:40:17.6793341Z       File "/builddir/sagemath-10.8/.xbps-testdir/1768205922/usr/lib/python3.14/site-packages/sage/misc/cython.py", line 620, in cython_import_all
2026-01-12T08:40:17.6794452Z         m = cython_import(filename, **kwds)
2026-01-12T08:40:17.6795672Z       File "/builddir/sagemath-10.8/.xbps-testdir/1768205922/usr/lib/python3.14/site-packages/sage/misc/cython.py", line 588, in cython_import
2026-01-12T08:40:17.6796968Z         name, build_dir = cython(filename, **kwds)
2026-01-12T08:40:17.6797802Z                           ~~~~~~^^^^^^^^^^^^^^^^^^
2026-01-12T08:40:17.6798866Z       File "/builddir/sagemath-10.8/.xbps-testdir/1768205922/usr/lib/python3.14/site-packages/sage/misc/cython.py", line 354, in cython
2026-01-12T08:40:17.6800296Z         standard_libs, standard_libdirs, standard_includes, aliases = _standard_libs_libdirs_incdirs_aliases()
2026-01-12T08:40:17.6801269Z                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
2026-01-12T08:40:17.6804054Z       File "sage/misc/cachefunc.pyx", line 1045, in sage.misc.cachefunc.CachedFunction.__call__
2026-01-12T08:40:17.6813154Z         w = self.f(*args, **kwds)
2026-01-12T08:40:17.6814336Z       File "/builddir/sagemath-10.8/.xbps-testdir/1768205922/usr/lib/python3.14/site-packages/sage/misc/cython.py", line 52, in _standard_libs_libdirs_incdirs_aliases
2026-01-12T08:40:17.6815559Z         aliases = cython_aliases()
2026-01-12T08:40:17.6816529Z       File "/builddir/sagemath-10.8/.xbps-testdir/1768205922/usr/lib/python3.14/site-packages/sage/env.py", line 410, in cython_aliases
2026-01-12T08:40:17.6817730Z         lib = get_cblas_pc_module_name()
2026-01-12T08:40:17.6818777Z       File "/builddir/sagemath-10.8/.xbps-testdir/1768205922/usr/lib/python3.14/site-packages/sage/env.py", line 333, in get_cblas_pc_module_name
2026-01-12T08:40:17.6820119Z         return next(blas_lib for blas_lib in cblas_pc_modules if pkgconfig.exists(blas_lib))
2026-01-12T08:40:17.6820836Z     StopIteration
2026-01-12T08:40:17.6821223Z **********************************************************************
2026-01-12T08:40:17.6821888Z File "sage/misc/session.pyx", line 294, in sage.misc.session.save_session
2026-01-12T08:40:17.6822486Z Failed example:
2026-01-12T08:40:17.6822830Z     save_session(tmp_f, verbose=True)
2026-01-12T08:40:17.6823235Z Expected:
2026-01-12T08:40:17.6823588Z     ...
2026-01-12T08:40:17.6823933Z     Not saving g: g is a cython function or method
2026-01-12T08:40:17.6824563Z Got:
2026-01-12T08:40:17.6824824Z     Saving __name__
2026-01-12T08:40:17.6825119Z     Saving __doc__
2026-01-12T08:40:17.6825427Z     Saving __loader__
2026-01-12T08:40:17.6825753Z     Saving __spec__
2026-01-12T08:40:17.6826065Z     Saving __file__
2026-01-12T08:40:17.6826375Z     Saving __cached__
2026-01-12T08:40:17.6828097Z     Not saving input_box: input_box is a function or method
2026-01-12T08:40:17.6828804Z     Not saving text_control: text_control is a class or type
2026-01-12T08:40:17.6829413Z     Not saving slider: slider is a function or method
2026-01-12T08:40:17.6830026Z     Not saving range_slider: range_slider is a function or method
2026-01-12T08:40:17.6830671Z     Not saving checkbox: checkbox is a function or method
2026-01-12T08:40:17.6831286Z     Not saving selector: selector is a function or method
2026-01-12T08:40:17.6831887Z     Not saving input_grid: input_grid is a function or method
2026-01-12T08:40:17.6832576Z     Not saving color_selector: color_selector is a function or method
2026-01-12T08:40:17.6833144Z     Saving interact
2026-01-12T08:40:17.6833506Z     Not saving Path: Path is a class or type
2026-01-12T08:40:17.6833950Z     Saving tmp_f
2026-01-12T08:40:17.6834234Z     Saving a
2026-01-12T08:40:17.6834552Z     Not saving f: f is a function or method
2026-01-12T08:40:17.6863187Z **********************************************************************
2026-01-12T08:40:17.6865681Z 1 item had failures:
2026-01-12T08:40:17.6868797Z    2 of  15 in sage.misc.session.save_session
2026-01-12T08:40:17.7057617Z     [61 tests, 2 failures, 0.12s wall]
```
Is this also known?

**Comment by antonio-rojas** [comment]
> One more thing: using the meson system, there are a few tests
> 
> ```
> sage/misc/session.pyx  # 2 doctests failed
> sage/env.py  # 2 doctests failed
> sage/repl/load.py  # 2 doctests failed
> sage/repl/ipython_tests.py  # 3 doctests failed
> sage/rings/tate_algebra_ideal.pyx  # 1 doctest failed
> ```
> 
> that now fail in a similar way with `pkgconfig.exists(blas_lib))`, but they pass if I install `cblas-devel`. This is with openblas-devel only (which used to work):

Indeed, there is a mismatch between the definitions of `CBLAS_PC_MODULES` in `env.py`:
```
CBLAS_PC_MODULES = var("CBLAS_PC_MODULES", "cblas:openblas:blas")
```
and the one in `config.py`:
```
# Colon-separated list of pkg-config modules to search for cblas functionality.
# We hard-code it here as cblas because configure (build/pkgs/openblas/spkg-configure.m4)
# always provides cblas.pc, if necessary by creating a facade pc file for a system BLAS.
CBLAS_PC_MODULES = "cblas"
```
The latter is true for sage-the-distro provided openblas, but may not be the case for distro packages.

In any case: this is already fixed in https://github.com/sagemath/sage/pull/40520 by removing this code.

**Comment by dkwo** [comment]
Thank you!

**Comment by orlitzky** [comment]
sageinspect is still busted with cython-3.2.5, but 3.3.0 will hopefully take care of it
