### ISSUE TITLE
OS X: some doctests fail with extra text "ninja: warning: Ignoring jobserver: Pipe-based protocol is not supported!"

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#40869]
### Steps To Reproduce

Running doctests in OS X 15.6.1, Sage 10.8.beta3, with various homebrew packages installed, I see doctest failures of this sort:
```
**********************************************************************
File "src/sage/env.py", line 22, in sage.env
Failed example:
    out = check_output([sys.executable, "-c", cmd], env=env).decode().strip()   # long time
Expected nothing
Got:
    ninja: warning: Ignoring jobserver: Pipe-based protocol is not supported! [ --jobserver-fds=3,4 -j -- TEST_FLAGS=--long TEST_TARGET=testlong]
**********************************************************************
```
and
```
**********************************************************************
File "src/sage/misc/sagedoc.py", line 32, in sage.misc.sagedoc
Failed example:
    os.system("sage -c \"if 'sphinx' in sys.modules: sys.exit(1)\"")
Expected:
    0
Got:
    ninja: warning: Ignoring jobserver: Pipe-based protocol is not supported! [ --jobserver-fds=3,4 -j -- TEST_FLAGS=--long TEST_TARGET=testlong]
    0
**********************************************************************
```
and several other files. 

### Expected Behavior

Doctests should pass.

### Actual Behavior

Doctests fail.

### Additional Information

One solution would be to add the appropriate string to the `do_fixup` method in `src/sage/doctest/parsing.py`.

### Environment

- **OS**: OS X 15.6.1, Xcode 26.0, with many homebrew packages
- **Sage Version**: 10.8.beta3

### Checklist

- [x] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [x] I have read the documentation and troubleshoot guide

**Comment by tobiasdiez** [comment]
Probably a result of https://github.com/sagemath/sage/blob/83b52a79babd619fcdd4c9eeb5760500cdfb92db/src/sage/doctest/forker.py#L1886C18-L1886C36, at least I have never seen it in a non-make setup.

**Comment by orlitzky** [comment]
These run sage to run the doctest runner to run sage to run a shell to run sage to see what happens tests are lunacy to begin with, but maybe this can be swept under the rug by upgrading to ninja-1.13.1 which does support the jobserver protocol under GNU Make 4.4 or later.

**Comment by user202729** [comment]
> These run sage to run the doctest runner to run sage to run a shell to run sage to see what happens tests are lunacy to begin with

I don't understand what's the issue. The best I can see is "if it raises an error, it can be hard to debug whether the bug is in the doctest runner or the underlying program", but the same thing can be said with any tester ever (e.g. if you use pytest, you get "run Python to run pytest to fork itself to run a shell to run sage", which means if you get a bug it might as well be a bug with pytest or an interference between pytest and sage in a shell), no?

**Comment by orlitzky** [comment]
Normally when you're running a test suite, you're testing the copy of the program you just built. Things like,

```
sage: os.system("sage -c \"if 'sphinx' in sys.modules: sys.exit(1)\"")
```

can jump out of the sandbox and test the wrong sage.

Sage running within the doctester has to guess how it's being run, and often mess with its own environment in order to test what it wants to test. One of the tests above:

```
    sage: env = {k:v for (k,v) in os.environ.items() if not k.startswith("SAGE_")}                                                                             
    sage: from subprocess import check_output                                                                                                                  
    sage: module_name = "sage.all"   # hide .all import from the linter                                                                                        
    sage: cmd  = f"from {module_name} import SAGE_ROOT, SAGE_LOCAL;"                                                                                           
    sage: cmd +=  "from os.path import samefile;"                                                                                                              
    sage: if SAGE_ROOT is None:                                                                                                                                
    ....:     cmd +=  "s1 = SAGE_ROOT is None;"                                                                                                                
    ....: else:                                                                                                                                                
    ....:     cmd += f"s1 = samefile(SAGE_ROOT, '{SAGE_ROOT}');"                                                                                               
    sage: cmd += f"s2 = samefile(SAGE_LOCAL, '{SAGE_LOCAL}');"                                                                                                 
    sage: cmd += "print(s1 and s2);"                                                                                                                           
    sage: out = check_output([sys.executable, "-c", cmd], env=env).decode().strip()   # long time                                                              
    sage: out == "True"                                                               # long time                                                              
    True   
```

Whatever it's doing would be a lot simpler if didn't have to overwrite the environment, try to ensure that we're running `python` and not `sage`, and pass an entire python file on the CLI as a string. (IIRC I wrote that and got it wrong at least once, while trying to fix the original that was also wrong.)

Particularly when it goes wrong (why is `sage -c` running ninja?) it's a lot easier to figure out why when you're not in an inception meme.

**Comment by jhpalmieri** [comment]
What do people think about the proposal in the ticket description:

> One solution would be to add the appropriate string to the do_fixup method in src/sage/doctest/parsing.py.

**Comment by orlitzky** [comment]
> What do people think about the proposal in the ticket description:
> 
> > One solution would be to add the appropriate string to the do_fixup method in src/sage/doctest/parsing.py.

I'm not opposed to a quick fix, but I think we should understand how random output from the build system is winding up in your doctests first. I can't even imagine how ninja is getting involved, but if the ninja output can get slurped up, it's probably not the only one.

**Comment by tobiasdiez** [comment]
First question to answer this would be: when exactly does the error happens? When you run `make test` or also when you use `sage -t`? Is it still there if you don't use editable install?

**Comment by orlitzky** [comment]
xref ninja upgrade: https://github.com/sagemath/sage/pull/40922

**Comment by user202729** [comment]
ninja has always been running in editable install (if some file changes), no?

**Comment by orlitzky** [comment]
It runs whenever you rebuild something with meson, but `sage -c` shouldn't cause anything to be rebuilt... and certainly `python -c` (in the first test) shouldn't.

I guess `make <something>` could trigger it, but if we're going to blame that, we have to explain how output from the build system got interleaved with the doctest output two processes deep.

**Comment by jhpalmieri** [comment]
I see the error messages after doing `./bootstrap && ./configure && make testlong` from a fresh Sage clone. This turns out to use homebrew's version of ninja, which is 1.13.1. I tried the upgrade at #40922 (together with `./configure --with-system-ninja_build=no`) and I get the same error messages. When I run the tests with `./sage ...`, I do not see the errors.

**Comment by tobiasdiez** [comment]
What's the output if you run it with `MESONPY_EDITABLE_VERBOSE` set? Also please try the non-editable install of sage (there should be a configure flag for that).

**Comment by jhpalmieri** [comment]
> What's the output if you run it with `MESONPY_EDITABLE_VERBOSE` set? 

Tests pass.

> Also please try the non-editable install of sage (there should be a configure flag for that).

Tests also pass here. (In both cases I first did `make distclean`. In the second case I used `./configure --disable-editable`.)

**Comment by tobiasdiez** [comment]
> > What's the output if you run it with `MESONPY_EDITABLE_VERBOSE` set?
> 
> Tests pass.

This is super confusing. It should have printed a lot more debug output.

> 
> > Also please try the non-editable install of sage (there should be a configure flag for that).
> 
> Tests also pass here. (In both cases I first did `make distclean`. In the second case I used `./configure --disable-editable`.)

Thanks, so this confirms that it's indeed a ninja process that gets triggered by the automatic behind-the-scenes rebuild in the editable mode. But I have no idea how the options you pass to make (or better that make uses for recursive runs of make commands) ends up being passed to ninja...

Either way, it's probably a good idea anyway to minimize interconnected build systems - so I would suggest to just use `./sage -t` over `make whatevertest`

**Comment by user202729** [comment]
> > > What's the output if you run it with `MESONPY_EDITABLE_VERBOSE` set?
> > 
> > 
> > Tests pass.
> 
> This is super confusing. It should have printed a lot more debug output.

one possibility is because the warning is just a **warning**, ninja get ran and rebuild the thing anyway, so the net result is test only fail the first time.

… wait, distclean might exclude that possibility. Still, nothing says there is another bug in Makefile hide that bug. That can be ruled out if, after one case where tests pass with e.g. `MESONPY_EDITABLE_VERBOSE` set, a subsequent run without it fail again.

**Comment by jhpalmieri** [comment]
Okay, I took a fresh clone of the Sage git repo, set `MESONPY_EDITABLE_VERBOSE=yes`. Tests passed. Within the same directory, I unset that variable, ran `make distclean` and built again. The test failures appeared again.

**Comment by user202729** [comment]
actually the logic in `_sagemath_editable_loader.py` looks like this.

```
            if self._verbose or bool(env.get(VERBOSE, '')):
                # We want to show some output only if there is some work to do.
                if self._work_to_do(env):
                    build_command = ' '.join(self._build_cmd)
                    print(f'meson-python: building {self._name}: {build_command}', flush=True)
                    subprocess.run(self._build_cmd, cwd=self._build_path, env=env, check=True)
            else:
                subprocess.run(self._build_cmd, cwd=self._build_path, env=env, stdout=subprocess.DEVNULL, check=True)
```

If `MESONPY_EDITABLE_VERBOSE` is set, `ninja` is only run if there's _work_to_do. If it's unset, `ninja` is always run.

At least we narrow down the location of the issue, I suppose.

The other question is why does the wrong version of `ninja` get pick up?

**Comment by user202729** [comment]
@jhpalmieri if you're using the editable meson install, try looking at the `$CONDA_PREFIX/lib/python3.11/site-packages/_sagemath_editable_loader.py` (or whatever equivalent on your machine) and see what the last line is.

on my machine it's something like

```
install(
    'sagemath',
    {'share', 'sage'},
    '<build directory>',
    ['.../bin/ninja', '-j3'],
    False,
)
```

to find the location you can do

```
sage: import _sagemath_editable_loader
sage: _sagemath_editable_loader.__file__
```

**Comment by jhpalmieri** [comment]
I see this:
```
install(
    'sagemath',
    {'sage', 'share'},
    '/Users/palmieri/Sage/TESTING/sage-10.8.beta5/build/sage-distro',
    ['/opt/homebrew/bin/ninja'],
    False,
)
```
If I use `./configure --with-system-ninja_build=no`, I see this:
```
install(
    'sagemath',
    {'sage', 'share'},
    '/Users/palmieri/Sage/TESTING/sage-10.8.beta5/build/sage-distro',
    ['/Users/palmieri/Sage/TESTING/age-10.8.beta5/local/bin/ninja'],
    False,
)
```

**Comment by vbraun** [comment]
This is tripping over the old make jobserver protocol, and ninja only supports the new fifo-based jobserver. But MacOS ships with an old make. This is nothing that a ninja upgrade will ever fix as I don't think they'll ever add suport for the old-style make jobserver protocol.

In any case we should be able to run the tests from an old-style make jobserver, e.g. if the user wants to automate running tests. Just telling the user to invoke the test runner differently will never reliably avoid it.

Ignoring the warning in do_fixup is the proper fix

**Comment by user202729** [comment]
I guess seeing the warning every time sage starts is mostly harmless, so that's fine.

On the other hand, where did the `--jobserver-fds` come from? The `MAKE` environment variable, I guess?

**Comment by jhpalmieri** [comment]
> I guess seeing the warning every time sage starts is mostly harmless, so that's fine.

Who sees the warning every time Sage starts? I haven't seen those reports.

**Comment by user202729** [comment]
hm, I think I mean to say _worst case_ that happens. Reading the source code (https://github.com/sagemath/sage/issues/40869#issuecomment-3379120866) ninja is in fact invoked every time sage starts.

If it doesn't print the warning every time then it's something specific to the doctest environment that trigger the warning which is… mostly harmless…? although it's possible that someone happen to have the same environment variables set in a "normal" (or some programmatic invocation situation) shell.

**Comment by orlitzky** [comment]
This is just _one_ ninja warning though. A rebuild (a no-op in this case) is being triggered. If you edit a pyx file while `sage -t` is running, will these tests fail because sage stopped to rebuild stuff?

Ninja is a special case because warnings from ninja will be shown even when there's nothing to do, but I still think the issue runs deeper.

The only useful thing this test is doing is making sure that `import sage.all` works with the `SAGE_*` variables unset. Pytest already does this, but if we want to make it explicit (by unsetting those variables temporarily), it can easily be done without running sage in a subprocess, i.e. without triggering the rebuild: https://github.com/sagemath/sage/pull/40882#issuecomment-3353143509

(I haven't looked at the other failing test, but I'll eat my shoes if there isn't some way to rewrite it without the subprocess.)

**Comment by dimpase** [comment]
> This is tripping over the old make jobserver protocol, and ninja only supports the new fifo-based jobserver. But MacOS ships with an old make. This is nothing that a ninja upgrade will ever fix as I don't think they'll ever add suport for the old-style make jobserver protocol.

@jhpalmieri - you could try 
```
% brew install make
...
GNU "make" has been installed as "gmake".
If you need to use it as "make", you can add a "gnubin" directory
to your PATH from your bashrc like:

    PATH="/usr/local/opt/make/libexec/gnubin:$PATH"

% export PATH="$(brew --prefix)/opt/make/libexec/gnubin:$PATH"
% which make
/usr/local/opt/make/libexec/gnubin/make
% make -v
GNU Make 4.4.1
```

If @vbraun is (as usual) correct, this should make these errors go away.

(PS. in your case the output instead of `/usr/local/` should be `/opt/homebrew/`, but the `export` command
should be working any any kind of Homebrew, arm or intel)

**Comment by dimpase** [comment]
so I'll add `make` to ` build/pkgs/_prereq/distros/homebrew.txt` and `export PATH="$(brew --prefix)/opt/make/libexec/gnubin:$PATH"` to `.homebrew-build-env`.

And add a test for make version not to be too vintage.

**Comment by jhpalmieri** [comment]
> so I'll add `make` to ` build/pkgs/_prereq/distros/homebrew.txt` and `export PATH="$(brew --prefix)/opt/make/libexec/gnubin:$PATH"` to `.homebrew-build-env`.
> 
> And add a test for make version not to be too vintage.

If I understand this correctly, this means that OS X users who do not use homebrew and do not install GNU make a different way will still see these failures?

**Comment by dimpase** [comment]
I proposed to add a check on the make version which would make ./configure to error out on the Apple's make. We can have an option to allow an old make, with a suitable warning

**Comment by dimpase** [comment]
tests need not go via make, so this is not crucial.
And with a general idea of moving all testing to pytest, this is only temporary

**Comment by jhpalmieri** [comment]
I think in particular that since Sage builds fine (as far as I can tell) and the problem is only with doctests, having `./configure` raise an error if GNU make is not available seems extreme. Issuing a warning would be more appropriate.

**Comment by jhpalmieri** [comment]
Going back to my original post, what's wrong with the proposal to "add the appropriate string to the `do_fixup` method in `src/sage/doctest/parsing.py`? We've done this in the past for what seem to be similar cases.

**Comment by dimpase** [comment]
nothing is wrong with this

**Comment by orlitzky** [comment]
There was a discussion recently on the mailing list about making the background-rebuild process more verbose. If we do that, then we would need to `do_fixup` the whole build process.

There are only two problematic tests. The first one I think could be deleted, but there may still be some value in moving part of it to pytest (see https://github.com/sagemath/sage/pull/40882#issuecomment-3353143509). The second is,

```
sage: os.system("sage -c \"if 'sphinx' in sys.modules: sys.exit(1)\"")
```

which, since there are no comments, I can only assume is there to ensure that nobody puts `import sphinx` in sage library code. That is already tested somewhat because sagelib doesn't depend on sphinx unless you install it with pip... but in any case, it would be just as easy to test in the running sage by importing `sage.all`. That's what the repl does, so if you `import sage.all` and if sphinx isn't there, it won't be there in a new sage shell, either.

Fix/eliminate/update/whatever those two tests and there's no issue with background rebuilds.

**Comment by orlitzky** [comment]
Actually, the first test was deleted when https://github.com/sagemath/sage/pull/40882 was merged. That leaves only the sphinx test which should be an easy fix.

**Comment by dimpase** [comment]
> Actually, the first test was deleted when https://github.com/sagemath/sage/pull/40882 was merged. That leaves only the sphinx test which should be an easy fix.
> 
what was merged was #40327, not #40882

**Comment by dimpase** [comment]
> There was a discussion recently on the mailing list about making the background-rebuild process more verbose. If we do that, then we would need to `do_fixup` the whole build process.
> 
I don't understand this. When tests are being run, sagelib source is not changed, so everything is pre-build, no background-build is taking place.

**Comment by jhpalmieri** [comment]
> Actually, the first test was deleted when [#40882](https://github.com/sagemath/sage/pull/40882) was merged. That leaves only the sphinx test which should be an easy fix.

Those are not the only failures — when I said "I see doctests of this sort", that was supposed to imply that these were a sample of the kinds of failures, not a complete list. More examples:

```
**********************************************************************
File "src/sage/misc/sagedoc.py", line 31, in sage.misc.sagedoc
Failed example:
    os.system("sage -c \"if 'sphinx' in sys.modules: sys.exit(1)\"")
Expected:
    0
Got:
    ninja: warning: Ignoring jobserver: Pipe-based protocol is not supported! [ --jobserver-fds=3,4 -j -- TEST_FLAGS=--long TEST_TARGET=testlong]
    0
**********************************************************************
```

```
**********************************************************************
File "src/sage/plot/plot.py", line 521, in sage.plot.plot
Failed example:
    os.system("sage -c \"if 'matplotlib' in sys.modules: sys.exit(1)\"")  # long time
Expected:
    0
Got:
    ninja: warning: Ignoring jobserver: Pipe-based protocol is not supported! [ --jobserver-fds=3,4 -j -- TEST_FLAGS=--long TEST_TARGET=testlong]
    0
**********************************************************************
```

```
**********************************************************************
File "src/sage/repl/interpreter.py", line 728, in sage.repl.interpreter.get_test_shell
Failed example:
    out + err
Expected:
    ''
Got:
    'ninja: warning: Ignoring jobserver: Pipe-based protocol is not supported! [ --jobserver-fds=3,4 -j -- TEST_FLAGS=--long TEST_TARGET=testlong]\n'
**********************************************************************
```

plus some similar failures in other files plus a bunch of failures in `tests/cmdline.py`.

**Comment by orlitzky** [comment]
> 
> what was merged was [#40327](https://github.com/sagemath/sage/pull/40327), not [#40882](https://github.com/sagemath/sage/pull/40882)

Well the test is gone :)

**Comment by orlitzky** [comment]
> I don't understand this. When tests are being run, sagelib source is not changed, so everything is pre-build, no background-build is taking place.

I make edits all the time while the tests are running, I can't be the only one.

I can't test right now so I apologize for the potential FUD, but I know that `os.system()` tests the wrong sage executable in some cases, and that might cause a surprise rebuild too. `PYTHONPATH` should load the correct sagelib, but isn't it "sage" that triggers a rebuild?

**Comment by dimpase** [comment]
> > so I'll add `make` to ` build/pkgs/_prereq/distros/homebrew.txt` and `export PATH="$(brew --prefix)/opt/make/libexec/gnubin:$PATH"` to `.homebrew-build-env`.
> > And add a test for make version not to be too vintage.
> 
> If I understand this correctly, this means that OS X users who do not use homebrew and do not install GNU make a different way will still see these failures?

Apple's /usr/bin/make is still a GNU Make, a 20 years old version, 3.81.
Homebrew isn't the only way to get an up to day make on macOS; building GNU Make from source does not need anything beyond pre-reqs for building Sage. (A C compiler, and make, is all what's needed). So I propose to close this as "not planned".

**Comment by jhpalmieri** [comment]
I am not seeing these failures, so I am happy to close this. Feel free to adjust the tags as necessary.
