### ISSUE TITLE
Some doctests fails in python3.14.0

### ISSUE THREAD

**Issue by cxzhong** [sagemath/sage#41028]
```
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/sets/recursively_enumerated_set.pyx  # 3 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/doc/en/thematic_tutorials/tutorial-programming-python.rst  # 2 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/combinat/diagram_algebras.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/combinat/finite_state_machine.py  # 3 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/combinat/words/word.py  # 4 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/env.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/geometry/polyhedron/base4.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/geometry/polyhedron/base_mutable.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/graphs/base/c_graph.pyx  # 2 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/graphs/bipartite_graph.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/graphs/digraph.py  # 2 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/graphs/connectivity.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/graphs/generic_graph.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/graphs/graph.py  # 3 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/algebras/jordan_algebra.py  # Timed out
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/matrix/matrix0.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/misc/classcall_metaclass.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/misc/constant_function.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/misc/cachefunc.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/misc/lazy_list.pyx  # 7 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/misc/sage_unittest.py  # 2 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/misc/sagedoc.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/misc/session.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/misc/sageinspect.py  # 45 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/misc/superseded.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/misc/weak_dict.pyx  # 5 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/modules/with_basis/indexed_element.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/parallel/decorate.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/plot/colors.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/repl/ipython_tests.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/rings/polynomial/ore_polynomial_element.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/sets/disjoint_set.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/sets/set_from_iterator.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/structure/list_clone.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/structure/sage_object.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/topology/simplicial_complex.py  # 1 doctest failed
```

**Comment by cxzhong** [comment]
Some exceptions raised messages changed in python 3.14.0

**Comment by cxzhong** [comment]
like 
```
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/graphs/digraph.py
```
- Python < 3.14: TypeError: This graph is mutable, and thus not hashable. Create an immutable copy by g.copy(immutable=True)
- Python >= 3.14: TypeError: cannot use 'sage.graphs.digraph.DiGraph' as a dict key (This graph is mutable, and thus not hashable. Create an immutable copy by
   g.copy(immutable=True))

**Comment by cxzhong** [comment]
And for this
```
src/bin/sage -t --warn-long 5.0 --random-seed=99685026403890550082918489937640664814 src/sage/algebras/jordan_algebra.py  # Timed out
```
when you run 
```
sage: F.<x,y,z> = FreeAlgebra(QQ)
sage: J = JordanAlgebra(F)
sage: J.gens()
```
It is not finished. Infinite loop.


Others are some deprecation warnings from upstream cython. I have reported this to cython team. @dimpase

**Comment by fchapoton** [comment]
For Jordan algebra, I tried to fix that in #41038

**Comment by cxzhong** [comment]
> For Jordan algebra, I tried to fix that in [#41038](https://github.com/sagemath/sage/pull/41038)

Thank you very much, can you link it to the issue?

**Comment by cxzhong** [comment]
In 10.8 beta7
```
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/doc/en/thematic_tutorials/tutorial-programming-python.rst  # 2 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/combinat/diagram_algebras.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/combinat/finite_state_machine.py  # 3 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/combinat/words/word.py  # 4 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/env.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/geometry/polyhedron/base4.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/geometry/polyhedron/base_mutable.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/graphs/base/c_graph.pyx  # 2 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/graphs/bipartite_graph.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/graphs/connectivity.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/graphs/generic_graph.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/graphs/graph.py  # 3 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/matrix/matrix0.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/misc/classcall_metaclass.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/misc/constant_function.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/misc/cachefunc.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/misc/lazy_list.pyx  # 7 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/misc/sage_unittest.py  # 2 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/misc/sagedoc.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/misc/session.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/misc/sageinspect.py  # 4 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/misc/superseded.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/misc/weak_dict.pyx  # 5 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/modules/with_basis/indexed_element.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/parallel/decorate.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/plot/colors.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/repl/ipython_tests.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/rings/polynomial/ore_polynomial_element.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/sets/disjoint_set.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/sets/recursively_enumerated_set.pyx  # 3 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/sets/set_from_iterator.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/structure/list_clone.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/structure/sage_object.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=34563153036370194646066321819816315757 src/sage/topology/simplicial_complex.py  # 1 doctest failed
```

**Comment by cxzhong** [comment]
https://github.com/cython/cython/issues/7211 I have report the cython issue to cython team.

**Comment by cxzhong** [comment]
Now with cython 3.1.5
```
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/graphs/graph.py  # 3 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/graphs/generic_graph.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/combinat/diagram_algebras.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/sets/recursively_enumerated_set.pyx  # 3 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/geometry/polyhedron/base_mutable.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/geometry/polyhedron/base4.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/matrix/matrix0.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/combinat/finite_state_machine.py  # 3 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/structure/sage_object.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/rings/real_mpfr.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/topology/simplicial_complex.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/graphs/base/c_graph.pyx  # 2 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/sets/set_from_iterator.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/graphs/bipartite_graph.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/modules/with_basis/indexed_element.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/plot/colors.py  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/misc/weak_dict.pyx  # 5 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/misc/sage_unittest.py  # 2 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/doc/en/thematic_tutorials/tutorial-programming-python.rst  # 2 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/structure/list_clone.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/combinat/words/word.py  # 4 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/sets/disjoint_set.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/misc/lazy_list.pyx  # 7 doctests failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/misc/classcall_metaclass.pyx  # 1 doctest failed
src/bin/sage -t --warn-long 5.0 --random-seed=84881330321997860826321665880698081769 src/sage/misc/constant_function.pyx  # 1 doctest failed
```
And with the infinite loop of Jordan Algebra's generation

**Comment by cxzhong** [comment]
Now all doctest fails have been fixed. we are ready for python 3.14

**Comment by dkwo** [comment]
With sage 10.8 on Void, I am still getting (among others) these two failures
```
sage/repl/interpreter.py
sage/repl/ipython_tests.py
```
Is it possible they are also related to Python 3.14?

Here is the output:
```
$ python3 -m sage.doctest /usr/lib/python3.14/site-packages/sage/repl/ipython_tests.py
Running doctests with ID 2026-01-06-10-04-54-dbc2581e.
Running with SAGE_LOCAL='/usr' and SAGE_VENV='/usr'
Using --optional=pip,sage
Features to be detected: 32_bit,4ti2,benzene,bliss,buckygen,conway_polynomials,coxeter3,csdp,cvxopt,cvxopt,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_cubic_hecke,database_ellcurves,database_graphs,database_jones_numfield,database_knotinfo,dot2tex,dvipng,ecm,flatter,fpylll,fricas,gap_package_atlasrep,gap_package_design,gap_package_grape,gap_package_guava,gap_package_hap,gap_package_polenta,gap_package_polycyclic,gap_package_qpa,gap_package_quagroup,gfan,giac,glucose,graphviz,imagemagick,info,ipython,jmol,jupymake,jupyter_sphinx,kenzo,khoca,kissat,latte_int,lrcalc_python,lrslib,mathics,matroid_database,mcqd,meataxe,meson_editable,mpmath,msolve,nauty,networkx,numpy,palp,pandoc,pdf2svg,pdftocairo,pexpect,phitigra,pillow,plantri,polytopes_db,polytopes_db_4d,pplpy,primecountpy,ptyprocess,pycosat,pycryptosat,pynormaliz,pyparsing,python_igraph,regina,requests,rpy2,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.groups,sage.libs.braiding,sage.libs.ecl,sage.libs.flint,sage.libs.gap,sage.libs.giac,sage.libs.homfly,sage.libs.linbox,sage.libs.m4ri,sage.libs.ntl,sage.libs.pari,sage.libs.singular,sage.misc.cython,sage.modular,sage.modules,sage.numerical.mip,sage.plot,sage.rings.complex_double,sage.rings.finite_rings,sage.rings.function_field,sage.rings.number_field,sage.rings.padics,sage.rings.polynomial.pbori,sage.rings.real_double,sage.rings.real_mpfr,sage.sat,sage.schemes,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,scipy,singular,sirocco,sloane_database,sphinx,symengine_py,sympy,tdlib,threejs,topcom
Doctesting 1 file.
python3 -m sage.doctest --warn-long 5.0 --random-seed=153514679819300604583080072649527384466 /usr/lib/python3.14/site-packages/sage/repl/ipython_tests.py
**********************************************************************
File "/usr/lib/python3.14/site-packages/sage/repl/ipython_tests.py", line 115, in sage.repl.ipython_tests
Failed example:
    shell.run_cell(u'%pinfo2 stl_int_vector')
Expected:
    ...
    cdef class stl_int_vector(SageObject):
        """
        Example class wrapping an STL vector.
    <BLANKLINE>
        EXAMPLES::
    <BLANKLINE>
    ...
        """
    <BLANKLINE>
        cdef vector[int] *data
        cdef string *name
    <BLANKLINE>
        def __cinit__(self):
            """
            The Cython constructor.
    <BLANKLINE>
            EXAMPLES::
    <BLANKLINE>
    ...
    File:   .../sage/tests/stl_vector.pyx
    Type:   type
    ...
Got:
    Error getting source: s must be a string
    Init signature: stl_int_vector(*args, **kwds)
    Docstring:     
       Example class wrapping an STL vector.
    <BLANKLINE>
       EXAMPLES:
    <BLANKLINE>
          sage: from sage.tests.stl_vector import stl_int_vector
          sage: v = stl_int_vector()
    Init docstring: Initialize self.  See help(type(self)) for accurate signature.
    File:           /builddir/sagemath-10.8/src/sage/tests/stl_vector.pyx
    Type:           type
    Subclasses:     
**********************************************************************
1 item had failures:
   1 of  22 in sage.repl.ipython_tests
    [23 tests, 1 failure, 1.03s wall]
----------------------------------------------------------------------
python3 -m sage.doctest --warn-long 5.0 --random-seed=153514679819300604583080072649527384466 /usr/lib/python3.14/site-packages/sage/repl/ipython_tests.py  # 1 doctest failed
----------------------------------------------------------------------
Total time for all tests: 1.2 seconds
    cpu time: 1.0 seconds
    cumulative wall time: 1.0 seconds
Features detected for doctesting: 
```
and
```
$ python3 -m sage.doctest /usr/lib/python3.14/site-packages/sage/repl/interpreter.py  
Running doctests with ID 2026-01-06-10-06-06-a222c30a.
Running with SAGE_LOCAL='/usr' and SAGE_VENV='/usr'
Using --optional=pip,sage
Features to be detected: 32_bit,4ti2,benzene,bliss,buckygen,conway_polynomials,coxeter3,csdp,cvxopt,cvxopt,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_cubic_hecke,database_ellcurves,database_graphs,database_jones_numfield,database_knotinfo,dot2tex,dvipng,ecm,flatter,fpylll,fricas,gap_package_atlasrep,gap_package_design,gap_package_grape,gap_package_guava,gap_package_hap,gap_package_polenta,gap_package_polycyclic,gap_package_qpa,gap_package_quagroup,gfan,giac,glucose,graphviz,imagemagick,info,ipython,jmol,jupymake,jupyter_sphinx,kenzo,khoca,kissat,latte_int,lrcalc_python,lrslib,mathics,matroid_database,mcqd,meataxe,meson_editable,mpmath,msolve,nauty,networkx,numpy,palp,pandoc,pdf2svg,pdftocairo,pexpect,phitigra,pillow,plantri,polytopes_db,polytopes_db_4d,pplpy,primecountpy,ptyprocess,pycosat,pycryptosat,pynormaliz,pyparsing,python_igraph,regina,requests,rpy2,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.groups,sage.libs.braiding,sage.libs.ecl,sage.libs.flint,sage.libs.gap,sage.libs.giac,sage.libs.homfly,sage.libs.linbox,sage.libs.m4ri,sage.libs.ntl,sage.libs.pari,sage.libs.singular,sage.misc.cython,sage.modular,sage.modules,sage.numerical.mip,sage.plot,sage.rings.complex_double,sage.rings.finite_rings,sage.rings.function_field,sage.rings.number_field,sage.rings.padics,sage.rings.polynomial.pbori,sage.rings.real_double,sage.rings.real_mpfr,sage.sat,sage.schemes,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,scipy,singular,sirocco,sloane_database,sphinx,symengine_py,sympy,tdlib,threejs,topcom
Doctesting 1 file.
python3 -m sage.doctest --warn-long 5.0 --random-seed=336028512000759611196432922297670035962 /usr/lib/python3.14/site-packages/sage/repl/interpreter.py
**********************************************************************
File "/usr/lib/python3.14/site-packages/sage/repl/interpreter.py", line 680, in sage.repl.interpreter.interface_shell_embed
Failed example:
    shell.run_cell('List( [1..10], IsPrime )')                                # needs sage.libs.gap
Expected:
    [ false, true, true, false, true, false, true, false, false, false ]
    <ExecutionResult object at ..., execution_count=None error_before_exec=None error_in_exec=None ...result=[ false, true, true, false, true, false, true, false, false, false ]>
Got:
    [ false, true, true, false, true, false, true, false, false, false ]
    <ExecutionResult object at ffff4e9afdf0, execution_count=1 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at ffff4e9afce0, raw_cell="List( [1..10], IsPrime )" transformed_cell="sage.repl.interpreter.logstr(r"""[ false, true, tr.." store_history=False silent=False shell_futures=True cell_id=None> result=[ false, true, true, false, true, false, true, false, false, false ]>
**********************************************************************
1 item had failures:
   1 of   4 in sage.repl.interpreter.interface_shell_embed
    [139 tests, 1 failure, 1.51s wall]
----------------------------------------------------------------------
python3 -m sage.doctest --warn-long 5.0 --random-seed=336028512000759611196432922297670035962 /usr/lib/python3.14/site-packages/sage/repl/interpreter.py  # 1 doctest failed
----------------------------------------------------------------------
Total time for all tests: 7.7 seconds
    cpu time: 1.6 seconds
    cumulative wall time: 1.5 seconds
Features detected for doctesting: sage.libs.gap,sage.symbolic
```
